# JSP ??
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.servlet.jsp.init-parameters.development=true

# MongoDB ??
spring.data.mongodb.uri=${MONGODB_URI}

spring.jackson.time-zone=Asia/Seoul

